spring.application.name=auth

#liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
#database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
#security
jwt.secret=${JWT_SECRET:myDefaultSecretKeyForLocalTests1234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}