spring.application.name=math

#liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
#database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/math_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
#rabbitmq
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
rabbitmq.queues.calculation=${RABBITMQ_CALC_QUEUE:rating.calculation.command}
#security
jwt.secret=${JWT_SECRET:myDefaultSecretKeyForLocalTests1234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}